sudo: required

language: java
before_install:
  - mkdir ci-dependencies
  - cd ci-dependencies
  - curl -O https://openskywalking.github.io/skywalking-ci-assist/jars/ojdbc14-10.2.0.4.0.jar
  - mvn install:install-file  -Dfile=ojdbc14-10.2.0.4.0.jar  -DgroupId=com.oracle  -DartifactId=ojdbc14 -Dversion=10.2.0.4.0 -Dpackaging=jar
  - curl -O https://openskywalking.github.io/skywalking-ci-assist/jars/resin-4.0.41.jar
  - mvn install:install-file  -Dfile=resin-4.0.41.jar  -DgroupId=com.caucho  -DartifactId=resin -Dversion=4.0.41 -Dpackaging=jar
  - cd ..

install:
  - ./mvnw clean install

